# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Release to NPM

on:
  release:
    types: [ "created" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing dependancies...
        run: npm install
      - name: Check if library passes code linting standards...
        run: npm run lint
      - name: ğŸ› ï¸ Building package to check for compile errors...
        run: npm run build


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Installing dependancies...
        run: npm install
      - name: ğŸ› ï¸ Building package for NPM...
        run: npm run build
      - name: ğŸ“¦ Publishing to NPM registry...
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
